prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        team: monitoring

    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

    podMonitorNamespaceSelector:
      matchNames:
        - model-serving

alertmanager:
  config:
    global:
      slack_api_url: ''
  alertmanagerSpec:
    alertmanagerConfigNamespaceSelector:
    alertmanagerConfigSelector:
    alertmanagerConfigMatcherStrategy:
      type: None