apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  # namespaceSelector:
  #   matchNames:
  #     - app
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s