replicaCount: 2

image:
  repository: lethanhhiep0220/ahs
  tag: latest

service:
  port: 8080
  type: ClusterIP

ingress:
  enabled: true
  host: api.example.com
  path: /

model:
  bucket: ahsys-480510-model-registry-internal
  name: hematology-model
  stage: production
  file: best_qint8.pt
